### PR TITLE
Wrap handleNextScreen in useCallback

### PR DESCRIPTION
**Pull request by esme**
## Description

Jira Ticket: CALL-3789

`handleNextScreen` renders whenever the DialingScreen component renders every second when the timer changes. We should wrap `handleNextScreen` in a useCallback with `screenIndex` dependency.
## Merge Checklist

| Q                        | A 
| ------------------------ | --------------
| Adds Documentation?      |
| Any Dependency Changes?  |
| Patch: Bug Fix?          | yes
| Minor: New Feature?      |
| Major: Breaking Change?  |

[BRAVE Checklist](https://github.com/HubSpot/calling-extensions-sdk/blob/master/SHIP_WITH_CARE.md)

- [x] I have read the BRAVE checklist and confirmed if the following is necessary.

| Q                              | A 
| ------------------------------ | --------------
| Backwards Compatible?          |
| Rollout/Rollback Plan?         | 
| Automated test coverage?       | 
| Verified that changes work?    | yes
| Expect Dependencies to Fail?   |

### CODE REVIEW

**Comment by alonso-cadenas** [comment]
@esme, there's still a weird behavior where the timer doesn't reset to 0 before start a call.

**Comment by esme** [comment]
> @esme, there's still a weird behavior where the timer doesn't reset to 0 before start a call.

@alonso-cadenas Thanks for catching this! I just put in a fix and you should see it in the preview once GH pages finishes the deployment.

**Comment by esme** [comment]
Hmm the changes aren't showing up in the preview even though the [GH action](https://github.com/HubSpot/calling-extensions-sdk/actions/runs/5084406614) ran successfully. It's working for me locally.

**Review by alonso-cadenas — APPROVED** [review]
Excellent! I can see it working in the preview.

**Pull request merged**
