### PR TITLE
Add toggle to enforce order of events in the demo minimal js

### PR DESCRIPTION
**Pull request by esme**
## Description

Jira Ticket: CALL-6601

Use `state.enforceButtonsOrder` to enforce order of events in the demo minimal js. It is set to false by default. This enables us to test asynchronous SDK events for inbound calling.

## Merge Checklist

| Q                        | A 
| ------------------------ | --------------
| Adds Documentation?      |
| Any Dependency Changes?  |
| Patch: Bug Fix?          | yes
| Minor: New Feature?      |
| Major: Breaking Change?  |

[BRAVE Checklist](https://github.com/HubSpot/calling-extensions-sdk/blob/master/SHIP_WITH_CARE.md)

- [ ] I have read the BRAVE checklist and confirmed if the following is necessary.

| Q                              | A 
| ------------------------------ | --------------
| Backwards Compatible?          |
| Rollout/Rollback Plan?         | 
| Automated test coverage?       | 
| Verified that changes work?    |
| Expect Dependencies to Fail?   |

### CODE REVIEW

**Comment by hemang-thakkar** [comment]
Would it be helpful if we add a button to toggle enforceButtonsOrder instead of doing thru console? just for easy testing

**Comment by alonso-cadenas** [comment]
@esme checking in on the status of this PR.

**Comment by esme** [comment]
As this supports a specific use case that isn't directly related to the CTI experience, could we follow up with a developer interface if needed?

**Comment by esme** [comment]
@hemang-thakkar Let me know if this PR is good to go!

**Review by alonso-cadenas — APPROVED** [review]

**Pull request merged**
