### PR TITLE
Send ownerId in onReady event

### PR DESCRIPTION
**Pull request by esme**
## Description

Jira Ticket: CALL-6409

Send ownerId in onReady event for Zoom.

## Merge Checklist

| Q                        | A 
| ------------------------ | --------------
| Adds Documentation?      |
| Any Dependency Changes?  |
| Patch: Bug Fix?          | 
| Minor: New Feature?      | yes
| Major: Breaking Change?  |

[BRAVE Checklist](https://github.com/HubSpot/calling-extensions-sdk/blob/master/SHIP_WITH_CARE.md)

- [x] I have read the BRAVE checklist and confirmed if the following is necessary.

| Q                              | A 
| ------------------------------ | --------------
| Backwards Compatible?          |
| Rollout/Rollback Plan?         | 
| Automated test coverage?       | 
| Verified that changes work?    |
| Expect Dependencies to Fail?   |

### CODE REVIEW

**Review by alonso-cadenas — APPROVED** [review]

**Comment by alonso-cadenas** [comment]
@esme I'd classify this change as a `minor` version improvement vs `patch` since the `ownerId` was never expected before.

**Comment by esme** [comment]
@alonso-cadenas In this case, should I run `publish:alpha:minor` instead of `publish:alpha`?

**Comment by alonso-cadenas** [comment]
@esme Yup!

**Comment by kangguru** [comment]
Hej, i've a problem with this :)

ownerId is undefined and userId is 0. What am i holding wrong that those values are not reported correctly onReady? portalId is present though.

**Comment by esme** [comment]
@kangguru Are you able to see ownerId in the `DIAL_NUMBER` event? The values may not be available in the onReady message yet.

**Comment by esme** [comment]
@kangguru Does the `DIAL_NUMBER` event work for you?

**Comment by kangguru** [comment]
Yea i think it does. But now i'm moving on the the 'new' calling window and it seems like all the ids are now where i expect them to be. thanks 👌

**Pull request merged**
